# Code Review Agent Configuration
version = "1.0"
[commands.code_review]
description = "Analyze code changes using Qodo Merge and provide categorized feedback"

instructions = """
You are an expert code reviewer. Your task is to:
Analyze ONLY the uncommited code changes using Qodo Merge improve tool
IF no staged changes exist, analyze ONLY the latest commit on the current branch.

**IMPORTANT: Your review scope is LIMITED to the uncommitted files only. OR if no uncommited files exist, your scope is LIMITED to the latest commit on the current branch.**

Do not enrich the results from Qodo Merge with any additional information or context.

Output:
Unless otherwise specified, return the results exactly as provided by Qodo Merge.
"""

# Arguments that can be passed to the agent
arguments = [
    { name = "target_branch", type = "string", required = false, default = "main", description = "Target branch to compare against" },
    { name = "exclude_files", type = "string", required = false, description = "Comma-separated list of file patterns to exclude" },
    { name = "output_format", type = "string", required = false, description = "String describtion of the desired output"}
]

# Tools available to this agent
tools = ["qodo_merge", "git", "filesystem"]

# Execution strategy: "act" for immediate execution, "plan" for multi-step planning
execution_strategy = "act"



# Code Review Agent Configuration
version = "1.0"

#  qodo diff_review --ui
 [commands.diff_review]
 description = "Review all the local commits in the local branch, and provide code suggestions via Qodo Merge"
 instructions = """
 1) Get the git diff of all the commits that are in the current local branch, but are not present in the main branch
 2) Use Qodo Merge 'improve' tool to generate code suggestions from this git diff.
 3) Take the exact output from the Qodo Merge 'improve' tool as a string, and present it as rendered markdown in the chat
 """
execution_strategy = "act"
available_tools = ["git", "filesystem", "qodo_merge"]

#  qodo diff_review_last_commit --ui
 [commands.diffreview_last_commit]
 description = "Review my latest local commit in the local branch, and provide code suggestions via Qodo Merge"
 instructions = """
 1) Get the git diff of the latest commit in the current local branch.
 2) Use Qodo Merge 'improve' tool to generate code suggestions from this git diff.
 3) Take the exact output from the Qodo Merge 'improve' tool as a string, and present it as rendered markdown in the chat
 """
execution_strategy = "act"
available_tools = ["git", "filesystem", "qodo_merge"]
