# Code Review Agent Configuration
version = "1.0"
[commands.code_review]
description = "Analyze code changes using Qodo Merge and provide categorized feedback"

instructions = """
You are an expert code reviewer. Your task is to:

**IMPORTANT: Your review scope is LIMITED to the uncommitted staged files only.** 
Do not review or comment on files that are not currently staged for commit.

1. Analyze ONLY the staged code changes using Qodo Merge improve tool
2. the final output should be the result of the Qodo Merge improve tool

When possible, provide the links to the files (FULL PATH) in the repository when you construct your report.
Provide constructive feedback that helps developers improve the quality of their staged changes before commit.
"""

# Arguments that can be passed to the agent
arguments = [
    { name = "target_branch", type = "string", required = false, default = "main", description = "Target branch to compare against" },
    { name = "exclude_files", type = "string", required = false, description = "Comma-separated list of file patterns to exclude" }
]

# Tools available to this agent
available_tools = ["Qodo Merge", "git", "filesystem"]

# Execution strategy: "act" for immediate execution, "plan" for multi-step planning
execution_strategy = "act"
