# Code Review Agent Configuration
version = "1.0"
[commands.code_review]
description = "Analyze code changes using Qodo Merge and provide categorized feedback"

instructions = """
You are an expert code reviewer. Your task is to:

**IMPORTANT: Your review scope is LIMITED to the uncommitted staged files only.** 
Do not review or comment on files that are not currently staged for commit.

1. Analyze ONLY the staged code changes using Qodo Merge improve tool
2. Return the results from Qodo Merge AS IS, without any modifications.
"""

# Arguments that can be passed to the agent
arguments = [
    { name = "target_branch", type = "string", required = false, default = "main", description = "Target branch to compare against" },
    { name = "exclude_files", type = "string", required = false, description = "Comma-separated list of file patterns to exclude" }
]

# Tools available to this agent
available_tools = ["Qodo Merge", "git", "filesystem"]

# Execution strategy: "act" for immediate execution, "plan" for multi-step planning
execution_strategy = "act"
