name: Update README for Merged PR

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to process for README update'
        required: true
        type: number
      repo_owner:
        description: 'Repository owner'
        required: false
        default: 'qodo-ai'
        type: string
      repo_name:
        description: 'Repository name'
        required: false
        default: 'agents'
        type: string
      base_branch:
        description: 'Base branch to create feature branch from'
        required: false
        default: 'main'
        type: string
      branch_prefix:
        description: 'Prefix for the new branch name'
        required: false
        default: 'docs/update-readme'
        type: string

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      issues: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Qodo Command
        run: |
          npm install -g @qodo/command
          qodo --version
      
      - name: Setup Python for MCP servers
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install MCP dependencies
        run: |
          pip install uvx
          uvx --version
      
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Run PR README Updater Agent
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd agents/pr-readme-updater
          qodo pr-readme-updater \
            --pr_number=${{ inputs.pr_number }} \
            --repo_owner=${{ inputs.repo_owner }} \
            --repo_name=${{ inputs.repo_name }} \
            --base_branch=${{ inputs.base_branch }} \
            --branch_prefix=${{ inputs.branch_prefix }}
      
      - name: Summary
        run: |
          echo "## 📝 README Update Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **PR Processed**: #${{ inputs.pr_number }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Repository**: ${{ inputs.repo_owner }}/${{ inputs.repo_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Base Branch**: ${{ inputs.base_branch }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch Prefix**: ${{ inputs.branch_prefix }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The agent has analyzed the merged PR and updated the README Community Agents section accordingly." >> $GITHUB_STEP_SUMMARY
          echo "Check the repository for the new documentation PR that was created." >> $GITHUB_STEP_SUMMARY